version: '{build}'

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - "%devkit%\\devkitvars.bat"
  - ruby --version
  - gem --version
  - bundle install

build: off

test_script:
  - bundle exec rake test TESTOPTS=-v

branches:
  only:
    - master

# https://www.appveyor.com/docs/installed-software/#ruby
environment:
  matrix:
    - ruby_version: "23-x64"
      devkit: C:\Ruby23-x64\DevKit
